---
# tasks file for nginx
# Creating a user.
- name: Create a user web user
  ansible.builtin.user:
    name: "{{ user_ceration }}"
    shell: "{{ user_shell }}"
    password: "{{ 'webuser' | password_hash('sha512') }}"
    state: present

# Installing nginx package.
- name: Install nginx package
  ansible.builtin.apt:
    name: "{{ package_name }}"
    state: present

# Adding index.html file to mentioned path.
- name: Copy index file
  ansible.builtin.copy:
    src: "{{ copy_index_file_path }}"
    dest: "{{ path_to_copyat }}"
    owner: "{{ user_ceration }}"
    group: "{{ user_ceration }}"
    mode: "{{ permission }}"
  register: Index_html_changed

# Configuring nginx.conf
- name: Configure nginx to listen on 8080 & change root path
  ansible.builtin.copy:
    src: "{{ src_nginx_config_file }}"
    dest: "{{ nginx_conffile_path }}"
    mode: "{{ permission }}"
  notify: Restart nginx service
    #  when: Index_html_changed.changed
